

### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "admin1",
    "password": "admin1"
}

### Create

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "admin1",
    "password": "admin1"
}

### post
POST http://localhost:5000/api/store
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmJlOWI3ZTU5NmExNjUzODEyY2VkNGYiLCJpYXQiOjE2NTY2NTg4MjN9.Axb4pwG90EX2iKMdrvTAbm5ssrnMHX01nd4JZ7xSLMo

{
    "item": "sasunf 78",
    "cost": 30000,
    "description":"this is ip"
}

### get
GET http://localhost:5000/api/store/
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmJkNTBkYjFlZDliNmZjYTA0YjMyZGQiLCJpYXQiOjE2NTY1ODEzNjV9.Yz3kepciE7MGGKCMyP0AvZRe1Su0BqDigixeULaeNLk

### get co id
GET http://localhost:5000/api/store/62be9b9b596a1653812ced54
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmJkNTBkYjFlZDliNmZjYTA0YjMyZGQiLCJpYXQiOjE2NTY1ODEzNjV9.Yz3kepciE7MGGKCMyP0AvZRe1Su0BqDigixeULaeNLk

### get co id
GET http://localhost:5000/api/store/user/admin1
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmJkNTBkYjFlZDliNmZjYTA0YjMyZGQiLCJpYXQiOjE2NTY1ODEzNjV9.Yz3kepciE7MGGKCMyP0AvZRe1Su0BqDigixeULaeNLk

###
GET http://localhost:5000/api/user/admin1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmJkNTBkYjFlZDliNmZjYTA0YjMyZGQiLCJpYXQiOjE2NTY1ODEzNjV9.Yz3kepciE7MGGKCMyP0AvZRe1Su0BqDigixeULaeNLk

