

### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "admin1",
    "password": "admin1"
}

### Create

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "admin1",
    "password": "admin1"
}

### post
POST http://localhost:5000/api/store
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmMxNmE2OWE1MDY5ODQ2Zjg0ZDc5YTUiLCJpYXQiOjE2NTY4NDI4NTh9.FXsxug7nhOZI-Hy3ERV5xVcKFDOd70fis7VuAm0-CvQ

{
    "item": "323232323 56",
    "cost": 30000,
    "description":"this issd"
}

### get
GET http://localhost:5000/api/store/
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmJkNTBkYjFlZDliNmZjYTA0YjMyZGQiLCJpYXQiOjE2NTY1ODEzNjV9.Yz3kepciE7MGGKCMyP0AvZRe1Su0BqDigixeULaeNLk

### get co id
GET http://localhost:5000/api/store/62be9b9b596a1653812ced54
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmJkNTBkYjFlZDliNmZjYTA0YjMyZGQiLCJpYXQiOjE2NTY1ODEzNjV9.Yz3kepciE7MGGKCMyP0AvZRe1Su0BqDigixeULaeNLk

### get co id
GET http://localhost:5000/api/store/user/admin1
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmJkNTBkYjFlZDliNmZjYTA0YjMyZGQiLCJpYXQiOjE2NTY1ODEzNjV9.Yz3kepciE7MGGKCMyP0AvZRe1Su0BqDigixeULaeNLk

###
GET http://localhost:5000/api/user/admin1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmJkNTBkYjFlZDliNmZjYTA0YjMyZGQiLCJpYXQiOjE2NTY1ODEzNjV9.Yz3kepciE7MGGKCMyP0AvZRe1Su0BqDigixeULaeNLk

###
POST http://localhost:5000/api/cart/admin1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmJkNTBkYjFlZDliNmZjYTA0YjMyZGQiLCJpYXQiOjE2NTY1ODEzNjV9.Yz3kepciE7MGGKCMyP0AvZRe1Su0BqDigixeULaeNLk

{
    "item": "62c16a60a5069846f84d799c",
    "quantity": 4
}