

### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "admin1",
    "password": "admin1"
}

### Create

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "admin2",
    "password": "admin2"
}

### post
POST http://localhost:5000/api/store
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmMzZjc0ZmU2ZjhmM2JlMDA4NjQ1MTIiLCJpYXQiOjE2NTcwMTAwMDB9.khtFleaDwXtHBzfXuA38dzWOZjsLLJI8MwG29smHzkk

{
    "item": "lt5",
    "cost": 30000,
    "description":"this issd"
}

### get
GET http://localhost:5000/api/store/
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmJkNTBkYjFlZDliNmZjYTA0YjMyZGQiLCJpYXQiOjE2NTY1ODEzNjV9.Yz3kepciE7MGGKCMyP0AvZRe1Su0BqDigixeULaeNLk

### get my store
GET http://localhost:5000/api/store/mystore
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmMxNmE2OWE1MDY5ODQ2Zjg0ZDc5YTUiLCJpYXQiOjE2NTcwMTAwNjl9.EHaAnXdvtiiTBdQmnyBFoo7Lw5zPXLc80AkFtCiQJAM

### get co id
GET http://localhost:5000/api/store/admin1
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmJkNTBkYjFlZDliNmZjYTA0YjMyZGQiLCJpYXQiOjE2NTY1ODEzNjV9.Yz3kepciE7MGGKCMyP0AvZRe1Su0BqDigixeULaeNLk

###
GET http://localhost:5000/api/user/admin1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmJkNTBkYjFlZDliNmZjYTA0YjMyZGQiLCJpYXQiOjE2NTY1ODEzNjV9.Yz3kepciE7MGGKCMyP0AvZRe1Su0BqDigixeULaeNLk

###
POST http://localhost:5000/api/cart/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmJkNTBkYjFlZDliNmZjYTA0YjMyZGQiLCJpYXQiOjE2NTY1ODEzNjV9.Yz3kepciE7MGGKCMyP0AvZRe1Su0BqDigixeULaeNLk

{
    "item": "62c16a60a5069846f84d799c",
    "quantity": 10,
}

###
GET http://localhost:5000/api/cart/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmMxNmE2OWE1MDY5ODQ2Zjg0ZDc5YTUiLCJpYXQiOjE2NTcwMDY3MzN9.trAwz7bTikhsFJUngJu0rPyVg7ZFUZ8ExhjOIX9FjPA


### 
POST http://localhost:5000/api/cart/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmMxNmE2OWE1MDY5ODQ2Zjg0ZDc5YTUiLCJpYXQiOjE2NTcwMTQwMjJ9.X0w3zBNcJ-cVfj4s9KM3EWsAsWpNF5od7dnKQS9dGLw

{
    "item": "62c3f743e6f8f3be00864507",
    "quantity": 20,
}

###

GET http://localhost:5000/api/cart/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmMxNmE2OWE1MDY5ODQ2Zjg0ZDc5YTUiLCJpYXQiOjE2NTcwMDkwNDF9.GyUkEtb37Pdcy17kDqZLNBSelTqS68vdzTprSxiUbCw

